### ISSUE TITLE
README.md mentions environment variable CAF_LOG_LEVEL, but it's a System property

### ISSUE THREAD

**Issue by dhsmith1001** [CAFapi/caf-logging#16]
In doing some testing of the CAFapi/opensuse-tomcat-image, I wanted to see debug & trace log messages. I saw the comment about CAF_LOG_LEVEL in the readme, so I added export CAF_LOG_LEVEL=TRACE to setenv.sh, without effect. I tried adding -DCAF_LOG_LEVEL=TRACE to JAVA_OPTS in setenv.sh, and that worked. It would be clearer if the readme referred to CAF_LOG_LEVEL as a System property in stead of an environment variable.

**Comment by dermot-hardy** [comment]
https://portal.digitalsafe.net/browse/SCMOD-9963

**Comment by dermot-hardy** [comment]
It definitely should be usable as an environment variable.  Looking at the logback configuration documentation [here](http://logback.qos.ch/manual/configuration.html#scopes) I see that it does say that it can be set as a system property, but should fallback to using it as an environment variable:

> During substitution, properties are looked up in the local scope first, in the context scope second, in the system properties scope third, and in the [OS environment](https://docs.oracle.com/javase/tutorial/essential/environment/env.html) fourth and last.

@michael-bryson Please confirm that this is working as expected.

**Comment by michael-bryson** [comment]
I tried the following:
`docker container run --rm -e CAF_LOG_LEVEL=INFO cafapi/opensuse-tomcat:4`
`docker container run --rm -e CAF_LOG_LEVEL=DEBUG cafapi/opensuse-tomcat:4`
In both cases the log output was as expected, i.e. INFO or DEBUG level.

This looks to be working as expected for me.

**Comment by dermot-hardy** [comment]
@dhsmith1001 Is it OK if I close this as not an issue?

**Comment by dhsmith1001** [comment]
Sure, I didn't realize that it needed to be set for the whole container. I was attempting to set it just for the tomcat process.
